### ISSUE TITLE
Cannot install on CentOS 7.3 with Redmine 3.3.3

### ISSUE THREAD

**Issue by bviktor** [akiko-pusu/redmine_issue_badge#60]
Here's the error message I'm getting:

~~~
[root@redminetest plugins]# rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /opt/redmine-3.3.3)
rspec failed.
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rspec failed.
rake aborted!
NoMethodError: private method `include' called for MyController:Class
/opt/redmine-3.3.3/plugins/redmine_issue_badge/init.rb:9:in `block in <top (required)>'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `call'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/share/gems/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/share/gems/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/share/gems/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/share/ruby/tsort.rb:150:in `block in tsort_each'
/usr/share/ruby/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/usr/share/ruby/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/share/ruby/tsort.rb:182:in `block in each_strongly_connected_component'
/usr/share/ruby/tsort.rb:180:in `each'
/usr/share/ruby/tsort.rb:180:in `each_strongly_connected_component'
/usr/share/ruby/tsort.rb:148:in `tsort_each'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/redmine-3.3.3/config/environment.rb:14:in `<top (required)>'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/share/gems/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
~~~

Please let me know if you need any more info. Thanks in advance.

**Comment by bviktor** [comment]
Fails with (soon-to-be-released) 3.4.0 too:

~~~
[root@redminetest plugins]# rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /opt/redmine-3.4.0)
rspec failed.
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rspec failed.
rake aborted!
NoMethodError: private method `include' called for MyController:Class
/opt/redmine-3.4.0/plugins/redmine_issue_badge/init.rb:9:in `block in <top (required)>'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `call'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/share/gems/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/share/gems/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/share/gems/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/share/ruby/tsort.rb:150:in `block in tsort_each'
/usr/share/ruby/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/usr/share/ruby/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/share/ruby/tsort.rb:182:in `block in each_strongly_connected_component'
/usr/share/ruby/tsort.rb:180:in `each'
/usr/share/ruby/tsort.rb:180:in `each_strongly_connected_component'
/usr/share/ruby/tsort.rb:148:in `tsort_each'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/redmine-3.4.0/config/environment.rb:14:in `<top (required)>'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/application.rb:328:in `require'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/share/gems/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/share/gems/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
~~~

**Comment by bviktor** [comment]
Okay, this is actually solved I believe. This was the hint:

https://github.com/alexreisner/geocoder/issues/1066

Also I have to put `gem "rspec"` into Redmine's `Gemfile.local` - I don't know how this can be achieved via the plugin's files. Will send a pull request soon.

**Comment by akiko-pusu** [comment]
Hi, @bviktor
Thanks for your issue report and pull request.
As following, support for Ruby 1.9.3, 2.0 and 2.1 has ended by Ruby community.
http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Requirements

Unless there is some particular reason, I hope to not to change. So, please let me know the version of ruby you use?  1.9 or 2.1?

Also Gemfile.local is required only for the testing (spec) of this plugin, there is nothing if "rspec failed.” message is shown.
I’m going to fix this warning message like this commit:
https://github.com/akiko-pusu/redmine_issue_templates/commit/d5b2c5ea6ce8ec9c96439de757e2f3fdaa3d6217

**Comment by bviktor** [comment]
Hi @akiko-pusu yes I know Ruby 2 is EOL'd but even the latest CentOS/RHEL still ships that. All our servers run CentOS :)

~~~
$ ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
~~~

This is CentOS 7.3.

Thanks a lot for omitting those errors!

**Comment by akiko-pusu** [comment]
Commit: 	630a474 was merged into master. Thanks for your help!

**Comment by bviktor** [comment]
Thanks a lot !
