### ISSUE TITLE
Breaks with Redmine 4 

### ISSUE THREAD

**Issue by bviktor** [akiko-pusu/redmine_issue_badge#91]
The plugin won't work with Redmine 4:

```
$ RAILS_ENV=production rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `alias_method_chain' for MyController:Class
Did you mean?  alias_method
/opt/redmine-4.0.1/plugins/redmine_issue_badge/lib/issue_badge/my_controller_patch.rb:5:in `block in <module:MyControllerPatch>'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/concern.rb:122:in `class_eval'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/concern.rb:122:in `append_features'
/opt/redmine-4.0.1/plugins/redmine_issue_badge/init.rb:11:in `include'
/opt/redmine-4.0.1/plugins/redmine_issue_badge/init.rb:11:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:347:in `each'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:347:in `call'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/opt/redmine-4.0.1/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.5/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/usr/local/rvm/gems/ruby-2.4.5/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.4.5/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-2.4.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.5/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.4.5/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
```

Apparently this method was deprecated with Rails 5.1, and Redmine 4 uses 5.2.2 (up from 4.2.8 in Redmine 3.4.6).

**Comment by kenji21** [comment]
Just sent PR https://github.com/akiko-pusu/redmine_issue_badge/pull/92

**Comment by akiko-pusu** [comment]
@kenji21 Thanks for PR #92 
I’ll apply above pull request against to Redmine4.x branch.
Please wait for a while!

**Comment by akiko-pusu** [comment]
@bviktor @kenji21 
Sorry for my delayed action to update this plugin.
Now development branch is ready for Redmine4.x and I'm going to release it soon.

**Comment by akiko-pusu** [comment]
New verson 0.1.0 has been released. If you have some Redmine4 which is clean installed, please try.

**Comment by kenji21** [comment]
sorry for late reply, upgraded to 0.1.2 today 💪

**Comment by ji8812** [comment]
plugin not workin in redmine docker version 40.6 or 4.1.0 

i tried all 0.1.0 0.1.2 0.1.3 all not working :(

**Comment by kenji21** [comment]
so this might be considered as a new issue @ji8812 , can you provide some error message in log files ?

**Comment by ji8812** [comment]
it seems your plugin is not compatible with redmine 4.1.0 docker

**Comment by ji8812** [comment]
can you adjust your plugin for 4.1.0 redmine docker

**Comment by ji8812** [comment]
send me the link here to download

**Comment by bviktor** [comment]
Can you please open a separate ticket for your issue, @ji8812 ?

**Comment by kenji21** [comment]
Just updated to 4.1.1, no issue
